require('./components/base/css/reset.css')
require('./components/lib/css/page.css')
//require('./components/lib/js/datejs')
require('./components/body/bill/zhangdan.css')
require('./components/body/sample/yangbengenzong.css')
require('./components/lib/js/datejs/need/laydate.css')
require('./components/lib/js/datejs/skins/default/laydate.css')
